- id: '1553724220138'
  alias: Luftaden.info-update
  trigger:
  - entity_id: sensor.terasse_luftruck
    platform: state
  condition: []
  action:
  - service: rest_command.rest_send_luftdaten_all
  - service: rest_command.rest_send_luftdaten_dust
  - service: rest_command.rest_send_luftdaten_htp
  - service: rest_command.rest_send_to_dump01
  - service: rest_command.rest_send_to_dump02
  - service: rest_command.rest_send_to_dump03
- id: alarm001
  alias: Terrassentüre öffnet
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: /DOOR_EZ1/State
    payload: OPEN
  condition:
    condition: state
    entity_id: input_boolean.terrace_door
    state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id:
    - input_boolean.terrace_door
  - service: notify.matrix_emi
    data:
      message: 'Die Terrassentüre hat sich geöffnet!'
- id: br_sunrise
  alias: Sonnenaufgang im Badezimmer
  initial_state: 'off'
  trigger:
  - platform: time
    at: '8:31:00'
  - platform: numeric_state
    entity_id: sensor.solar_angle
    above: 10
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: cover.bad_rollo
      state: closed
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: time
      after: 08:30:00
  action:
  - service: cover.open_cover
    entity_id: cover.bad_rollo
- id: br_sunset
  alias: Sonnenuntergang im Badezimmer
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.solar_angle
    below: 5
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.yr_wind_speed
      below: 10
    - condition: numeric_state
      entity_id: sensor.zamg_wind_max_speed
      below: 25
    - condition: state
      entity_id: cover.bad_rollo
      state: open
  action:
  - service: cover.close_cover
    entity_id: cover.bad_rollo
- id: alarm_clock
  alias: Wecker
  initial_state: 'on'
  trigger:
    platform: time
    at: '7:05:00'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.solar_angle
      below: 2
    - condition: state
      entity_id: group.schlafzimmer_rollos
      state: closed
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - service: light.turn_on
    entity_id:
    - light.schlafzimmer
- id: bedroom_sunrise
  alias: Sonnenaufgang im Schlafzimmer
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.solar_angle
    above: 2
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: cover.schlafzimmer_rollo_links
        state: closed
      - condition: state
        entity_id: cover.schlafzimmer_rollo_mitte
        state: closed
      - condition: state
        entity_id: cover.schlafzimmer_rollo_rechts
        state: closed
  action:
  - service: scene.turn_on
    entity_id: scene.bedroom_at_morning
  - service: light.turn_off
    entity_id:
    - light.schlafzimmer
- id: bedroom_day
  alias: Schlafzimmer Rollos Öffnen
  initial_state: 'on'
  trigger:
    platform: time
    at: '10:30:00'
  action:
  - service: cover.open_cover
    entity_id: cover.schlafzimmer_rollo_links
  - service: cover.open_cover
    entity_id: cover.schlafzimmer_rollo_mitte
  - service: cover.open_cover
    entity_id: cover.schlafzimmer_rollo_rechts
  - service: light.turn_off
    entity_id:
    - light.schlafzimmer
- id: bedroom_sunset
  alias: Sonnenuntergang im Schlafzimmer
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.solar_angle
    below: 1
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.yr_wind_speed
      below: 10
    - condition: numeric_state
      entity_id: sensor.zamg_wind_max_speed
      below: 25
  action:
  - service: cover.close_cover
    entity_id: cover.schlafzimmer_rollo_links
  - service: cover.close_cover
    entity_id: cover.schlafzimmer_rollo_mitte
  - service: cover.close_cover
    entity_id: cover.schlafzimmer_rollo_rechts
- id: '1553734220138'
  alias: Luftfeuchte Regler
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.schlafzimmer_feuchtigkeit
    above: 65
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: switch.mqtt_sw_1
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id:
    - switch.mqtt_sw_1
- id: '1553728137235'
  alias: Terrassentüre schließt
  trigger:
  - payload: CLOSE
    platform: mqtt
    topic: /DOOR_EZ1/State
  condition: []
  action:
  - data: {}
    entity_id:
      - input_boolean.terrace_door
    service: input_boolean.turn_off
