
# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

logger:
  default: warning
  logs:
#     homeassistant.core: debug
#     asyncio: debug
#     homeassistant.components.cloud.iot: debug
    homeassistant.components.device_tracker: debug
    homeassistant.components.python_script: debug
    homeassistant.components.rest_command: debug
    homeassistant.notify.rest: debug

# Enables configuration UI
config:

system_health:

# Discover some devices automatically
discovery:


# Enables support for tracking state changes over time
recorder:         !include config/recorder.yaml
influxdb:         !include config/influxdb.yaml

# View all events in a logbook and history
history:          !include config/history.yaml
logbook:          !include config/logbook.yaml

matrix:           !include config/matrix.yaml
notify:           !include config/notify.yaml

mqtt:             !include config/mqtt.yaml

# Track the sun
sun:

sensor:           !include_dir_merge_list config/sensors
binary_sensor:    !include config/binary_sensor.yaml
device_tracker:   !include config/device_tracker.yaml

switch:           !include config/switch.yaml
climate:          !include config/climate.yaml
vacuum:           !include config/vacuum.yaml

input_datetime:   !include config/input_datetime.yaml
cover:            !include config/cover.yaml

speedtestdotnet:
  scan_interval:
    minutes: 20
  monitored_conditions:
    - ping
    - download
    - upload

rest_command: !include config/rest_command.yaml

# Enables a map showing the location of tracked devices
map:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

