### Dielen Licht mit verzögerung ausschalten
- id: foyer_light_off_with_delay
  alias: 'Dielen Licht mit verzögerung ausschalten'
  initial_state: 'on'
  trigger:
    #~ platform: mqtt
    #~ topic: /LIGHT_VZ1/State
    #~ payload: '100'
    platform: state
    entity_id: light.diele_hauptlicht
    to: 'on'
    for:
      minutes: 10
      seconds: 1
  action:
    - service:   light.turn_off
      entity_id:
      - light.diele_hauptlicht

### Stecker zum laden von staubsauger nach 12h abschallten
- id: switch_vac_off
  alias: 'Staubsauger lader aus'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: switch.switch_vac
    to: 'on'
    for:
      hours: 15
      minutes: 0
      seconds: 0
  action:
    - service:   switch.turn_off
      entity_id:
      - switch.switch_vac
