### Rollo Zimmer 1 am Morgen
- id: room_1_sunrise
  alias: 'Sonnenaufgang im Zimmer 1'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.solar_angle
    above: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: cover.zimmer1_rollo
        state: closed
  action:
    - service: cover.open_cover
      entity_id:  cover.zimmer1_rollo

- id: room_1_test
  alias: 'Zimmer 1 test'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.solar_angle
    above: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: cover.zimmer1_rollo
        state: closed
  action:
    - service: cover.set_cover_position
      position: 1.5
      entity_id: 
      - cover.zimmer1_rollo


### Rollo Zimmer 1 am Morgen
- id: room_1_sunset
  alias: 'Sonnenuntergang im Zimmer 1'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.solar_angle
      below: 1
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.yr_wind_speed_km
        below: 30
      - condition: numeric_state
        entity_id: sensor.zamg_wind_max_speed
        below: 30
      - condition: state
        entity_id: cover.zimmer1_rollo
        state: open
  action:
    - service: cover.close_cover
      entity_id:  cover.zimmer1_rollo
