# Schatten:

- platform: mqtt
  name: "Bad Rollo"
  availability_topic: 'shellies/blind-bad_1/online'
  command_topic:      'shellies/blind-bad_1/roller/0/command'
  position_topic:     'shellies/blind-bad_1/roller/0/pos'
  set_position_topic: 'shellies/blind-bad_1/roller/0/command/pos'
  value_template:     '{{ ( value | round(0) )}}'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  payload_available: 'true'
  payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Schlafzimmer Rollo links"
  availability_topic: 'shellies/blind-zimmer0_1/online'
  command_topic:      'shellies/blind-zimmer0_1/roller/0/command'
  position_topic:     'shellies/blind-zimmer0_1/roller/0/pos'
  set_position_topic: 'shellies/blind-zimmer0_1/roller/0/command/pos'
  value_template:     '{{ ( value | round(0) )}}'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  payload_available: 'true'
  payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Schlafzimmer Rollo mitte"
  availability_topic: 'shellies/blind-zimmer0_2/online'
  command_topic:      'shellies/blind-zimmer0_2/roller/0/command'
  position_topic:     'shellies/blind-zimmer0_2/roller/0/pos'
  set_position_topic: 'shellies/blind-zimmer0_2/roller/0/command/pos'
  value_template:     '{{ ( value | round(0) )}}'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  payload_available: 'true'
  payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Schlafzimmer Rollo rechts"
  availability_topic: 'shellies/blind-zimmer0_3/online'
  command_topic:      'shellies/blind-zimmer0_3/roller/0/command'
  position_topic:     'shellies/blind-zimmer0_3/roller/0/pos'
  set_position_topic: 'shellies/blind-zimmer0_3/roller/0/command/pos'
  value_template:     '{{ ( value | round(0) )}}'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  payload_available: 'true'
  payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Zimmer1 Rollo"
  # availability_topic: 'shellies/blind-zimmer1_1/online'
  command_topic:      'shellies/blind-zimmer1_1/roller/0/command'
  position_topic:     'shellies/blind-zimmer1_1/roller/0/pos'
  set_position_topic: 'shellies/blind-zimmer1_1/roller/0/command/pos'
  value_template:     '{{ ( value | round(0) )}}'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  # payload_available: 'true'
  # payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false
  
- platform: mqtt
  name: "Zimmer2 Rollo"
  # availability_topic: 'shellies/blind-zimmer2_1/online'
  command_topic:      'shellies/blind-zimmer2_1/roller/0/command'
  position_topic:     'shellies/blind-zimmer2_1/roller/0/pos'
  set_position_topic: 'shellies/blind-zimmer2_1/roller/0/command/pos'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  # payload_available: 'true'
  # payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Wohnraum Rollo Kochen"
  availability_topic: 'shellies/blind-zimmer3_1/online'
  command_topic:      'shellies/blind-zimmer3_1/roller/0/command'
  position_topic:     'shellies/blind-zimmer3_1/roller/0/pos'
  set_position_topic: 'shellies/blind-zimmer3_1/roller/0/command/pos'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  payload_available: 'true'
  payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Wohnraum Rollo Essen"
  availability_topic: 'shellies/blind-zimmer3_2/online'
  command_topic:      'shellies/blind-zimmer3_2/roller/0/command'
  position_topic:     'shellies/blind-zimmer3_2/roller/0/pos'
  set_position_topic: 'shellies/blind-zimmer3_2/roller/0/command/pos'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  payload_available: 'true'
  payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Wohnraum Rollo Coutch"
  # availability_topic: 'shellies/blind-zimmer3_3/online'
  command_topic:      'shellies/blind-zimmer3_3/roller/0/command'
  position_topic:     'shellies/blind-zimmer3_3/roller/0/pos'
  set_position_topic: 'shellies/blind-zimmer3_3/roller/0/command/pos'
  qos: 0
  retain: false
  payload_open:  "open"
  payload_close: "close"
  payload_stop:  "stop"
  # payload_available: 'true'
  # payload_not_available: 'false'
  position_open: 100
  position_closed: 0
  optimistic: false
