# From https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/

# mich_status_dropdown:
#   name: Mich
#   options:
#     - Home
#     - Just Arrived
#     - Just Left
#     - Away
#     - Extended Away
#   initial: Home

# eva_status_dropdown:
#   name: Eva
#   options:
#     - Home
#     - Just Arrived
#     - Just Left
#     - Away
#     - Extended Away
#   initial: Home

# people_status_dropdown:
#   name: People
#   options:
#     - Present
#     - Just Arrived
#     - Just Left
#     - Absent
#     - Extended Away
#   initial: Present

# # wind_contitions_dropdown:
# #   name: Wind Contitions
# #   options:
# #     - Low
# #     - Medium
# #     - High

# entrance_status_dropdown:
#   name: Eingangstüre
#   options:
#     - Open
#     - Long Open
#     - Just Closed
#     - Closed
#   initial: Closed
