# wecker_woche:
#   name: Wochentagswecker
#   has_time: true

# wecker_we:
#   name: Wochenendwecker
#   has_time: true

# vac00_charge:
#   name: Staubsauger Ladedauer
#   has_date: false
#   has_time: true
