- platform: mqtt
  name: "Diele Hauptlicht"
  state_topic:   "/DI/LIGHT1/State"
  command_topic: "/DI/LIGHT1/set"
  payload_on: "on"
  payload_off: "off"
  state_value_template: '{{ value | replace("100", "on") | replace("0","off") }}'
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Küche Abwasch"
  state_topic:   "/Z4/LIGHT3/State"
  command_topic: "/Z4/LIGHT3/set"
  payload_on: "on"
  payload_off: "off"
  state_value_template: '{{ value | replace("100", "on") | replace("0","off") }}'
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Küche Insel"
  state_topic:   "/Z4/LIGHT4/State"
  command_topic: "/Z4/LIGHT4/set"
  payload_on: "on"
  payload_off: "off"
  state_value_template: '{{ value | replace("100", "on") | replace("0","off") }}'
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Stehlampe Coutch"
  state_topic:   "/Z4/LIGHT6/State"
  command_topic: "/Z4/LIGHT6/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Wohnzimmer Essecke"
  #~ state_topic: "/Z4/LIGHT2/State"
  command_topic: "/Z4/LIGHT2/set"
  brightness_state_topic: "/Z4/LIGHT2/State"
  brightness_command_topic: "/Z4/LIGHT2/pct"
  brightness_scale: 100
  #~ command_on_template: >
    #~ {%- if brightness is defined -%}
      #~ {{ brightness/2.55 }}
    #~ {%- else -%}
      #~ on
    #~ {%- endif -%}
  #~ command_off_template: '{{ "off" }}'
  #~ state_template: >
    #~ {% if value | int < 1 %}
      #~ off
    #~ {% else %}
      #~ on
    #~ {% endif %}
  #~ brightness_template: '{{ value | float * 2.55 }}'
  #~ brightness_value_template: '{{ value | float * 2.55 }}'
  qos: 0
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  on_command_type: 'brightness'

- platform: mqtt
  name: "Wohnzimmer Licht"
  #~ state_topic: "/Z4/LIGHT1/State"
  command_topic: "/Z4/LIGHT1/set"
  brightness_state_topic: "/Z4/LIGHT1/State"
  brightness_command_topic: "/Z4/LIGHT1/pct"
  brightness_scale: 100
  #~ command_on_template: >
    #~ {%- if brightness is defined -%}
      #~ {{ brightness/2.55 }}
    #~ {%- else -%}
      #~ on
    #~ {%- endif -%}
  #~ command_off_template: '{{ "off" }}'
  #~ state_template: >
    #~ {% if value | int < 1 %}
      #~ off
    #~ {% else %}
      #~ on
    #~ {% endif %}
  #~ brightness_template: '{{ value | float * 2.55 }}'
  #~ brightness_value_template: '{{ value | float * 2.55 }}'
  qos: 0
  payload_off: "off"
  optimistic: false
  on_command_type: 'brightness'
#  payload_on: "on"

#~ - platform: mqtt
  #~ name: "Brightness light"
  #~ state_topic: "office/light/status"
  #~ command_topic: "office/light/switch"
  #~ payload_off: "OFF"
  #~ brightness_state_topic: 'office/light/brightness'
  #~ brightness_command_topic: 'office/light/brightness/set'
  #~ on_command_type: 'brightness'

- platform: mqtt
  name: "Schlafzimmer"
  state_topic:   "/Z1/LIGHT1/State"
  command_topic: "/Z1/LIGHT1/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Schlafzimmer Michi"
  state_topic:   "/Z1/LIGHT2/State"
  command_topic: "/Z1/LIGHT2/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Schlafzimmer Eva"
  state_topic:   "/Z1/LIGHT3/State"
  command_topic: "/Z1/LIGHT3/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Zimmer 1"
  state_topic:   "/Z2/LIGHT1/State"
  command_topic: "/Z2/LIGHT1/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Zimmer 2"
  state_topic:   "/Z3/LIGHT1/State"
  command_topic: "/Z3/LIGHT1/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Badezimmer"
  state_topic:   "/BR/LIGHT1/State"
  command_topic: "/BR/LIGHT1/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Badezimmer Spiegel"
  state_topic:   "/BR/LIGHT2/State"
  command_topic: "/BR/LIGHT2/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0

- platform: mqtt
  name: "WC"
  state_topic:   "/WC/LIGHT1/State"
  command_topic: "/WC/LIGHT1/set"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
