broker: mqtt.lan
port: 1883
client_id: hass
keepalive: 600
username: !secret mqtt_user
password: !secret mqtt_pw
protocol: 3.1
discovery: true
discovery_prefix: hass
birth_message:
  topic: 'hass/status'
  payload: 'online'
  qos: 0
  retain: true
will_message:
  topic: 'hass/status'
  payload: 'offline'
  qos: 0
  retain: true
