# The recorder component is storing details in a database
purge_keep_days: 60
exclude:
  domains:
    - automation
    - group
    - history_graph
    - scene
    - weblink
  entities:
     - updater.updater
     - sun.sun
     - sensor.time
     - sensor.date
     - sensor.moon
     - sensor.sunset
     - sensor.sunrise
     - sensor.solar_angle
     - sensor.season
     - sensor.dusk
     - sensor.dawn
     - sensor.luft_mean
     - sensor.speed_dl_mean
     - sensor.speed_ping_mean
     - sensor.speed_ul_mean
     - sensor.yr_symbol
     - binary_sensor.workday_sensor
     - binary_sensor.solar_angle
