- platform: mqtt
  name: "MQTT Schlafzimmer Sensor1"
  state_topic: "plugs/zimmer0_1/POWER"
  command_topic: "plugs/zimmer0_1/cmnd/POWER"
  availability_topic: "plugs/zimmer0_1/LWT"
  json_attributes_topic: "plugs/zimmer0_1/STATE"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Switch Vac"
  state_topic: "plugs/vac00/POWER"
  command_topic: "plugs/vac00/cmnd/POWER"
  availability_topic: "plugs/vac00/LWT"
  json_attributes_topic: "plugs/vac00/STATE"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Switch Modem"
  state_topic: "plugs/modem/POWER"
  command_topic: "plugs/modem/cmnd/POWER"
  availability_topic: "plugs/modem/LWT"
  json_attributes_topic: "plugs/modem/STATE"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "MQTT Zimmer1 Sensor1"
  state_topic: "plugs/zimmer1_1/POWER"
  command_topic: "plugs/zimmer1_1/cmnd/POWER"
  availability_topic: "plugs/zimmer1_1/LWT"
  json_attributes_topic: "plugs/zimmer1_1/STATE"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
