- name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  radius: 100
  icon: mdi:account-multiple
- name: work_p1
  latitude:  !secret p1_work_latitude
  longitude: !secret p1_work_longitude
  radius: 300
  icon: mdi:account-multiple
- name: home_p1
  latitude:  !secret p1_home_latitude
  longitude: !secret p1_home_longitude
  radius: 200
  icon: mdi:account-multiple
- name: work_p2
  latitude:  !secret p2_work_latitude
  longitude: !secret p2_work_longitude
  radius: 300
  icon: mdi:account-multiple
- name: home_p2
  latitude:  !secret p2_home_latitude
  longitude: !secret p2_home_longitude
  radius: 200
  icon: mdi:account-multiple

- name: Realraum
  latitude:  !secret r3_lat
  longitude: !secret r3_lon
  radius: 200
