schlafzimmer:
  name: Schlafzimmer
  view: yes
  entities:
    - sensor.schlafzimmer_temperatur
    - sensor.schlafzimmer_feuchtigkeit
    - group.schlafzimmer_automations
    - group.schlafzimmer_rollos
    - group.schlafzimmer_licht

schlafzimmer_automations:
  view: no
  entities:
    - automation.sonnenaufgang_im_schlafzimmer
    - automation.sonnenuntergang_im_schlafzimmer

schlafzimmer_rollos:
  name: Schlafzimmer Rollos
  view: no
  entities:
    - cover.schlafzimmer_rollo_links
    - cover.schlafzimmer_rollo_mitte
    - cover.schlafzimmer_rollo_rechts

schlafzimmer_licht:
  view: no
  entities:
    - light.schlafzimmer
    - light.schlafzimmer_eva
    - light.schlafzimmer_michi
