environment:
  name: Wetterdaten
  view: no
  entities:
    - sun.sun
    - sensor.solar_angle
    - sensor.sunrise
    - sensor.sunset
    - sensor.zamg_sun_last_hour
    - sensor.moon
    - sensor.season
    - sensor.waqi_donboscokirche_kreuzung_karntnerstrasse_alte_poststrasse_austria
    - sensor.yr_cloudiness
    - sensor.yr_humidity
    - sensor.zamg_humidity
    - sensor.yr_precipitation
    - sensor.zamg_precipitation
    - sensor.zamg_pressure_sealevel
    - sensor.yr_pressure
    - sensor.zamg_pressure
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.zamg_temperature
    - sensor.yr_dewpoint_temperature
    - sensor.yr_wind_direction
    - sensor.zamg_wind_bearing
    - sensor.yr_wind_speed_km
    - sensor.zamg_wind_speed
    - sensor.zamg_wind_max_speed
    - sensor.zamg_dewpoint

weather_aut:
  name: Wetter Automations
  view: no
  entities:
    - automation.open_blind_if_wind
    - automation.close_blind_if_hot

wetter:
  name: Wetter
  view: yes
  entities:
    - group.weather_aut
    - group.environment
    - history_graph.wetter
