infrastructure:
  name: IT Infrastruktur
  view: yes
  entities:
    - group.infrastructure_sensors
    - history_graph.netzwerk_statistik
    - history_graph.server_graph
    - group.automation

infrastructure_sensors:
  name: IT Sensoren
  view: no
  entities:
    - sensor.cpu_use
    - sensor.ram_free
    - sensor.speedtest_download
    - sensor.speedtest_ping
    - sensor.speedtest_upload
    - binary_sensor.fhem
    - binary_sensor.mich_home
    - binary_sensor.pc_mich
    - binary_sensor.tel_eva
    - binary_sensor.tel_mich
    - binary_sensor.mailserver
