infrastructure:
  name: IT Infrastruktur
  view: yes
  entities:
    - group.infrastructure_sensors
    - history_graph.netzwerk_statistik
    - history_graph.server_graph
    - group.automation

infrastructure_sensors:
  name: IT Sensoren
  view: no
  entities:
    - sensor.cpu_use
    - sensor.ram_free
    - sensor.speedtest_download
    - sensor.speedtest_ping
    - sensor.speedtest_upload
    - binary_sensor.fhem
    - binary_sensor.mich_home
    - binary_sensor.pc_mich
    - binary_sensor.tel_eva
    - binary_sensor.tel_mich
    - binary_sensor.mailserver

all_sceens:
  view: no
  entities:
    - scene.all_blinds_closed
    - scene.all_blinds_opened
    - scene.all_lights_off
    - scene.bedroom_at_morning
    - scene.east_blinds_closed
    - scene.movies

all_automations:
  view: no
  entities:
    - automation.alle_lichter_mit_fernbedienung_ausschalten
    - automation.dielen_licht_mit_verzogerung_ausschalten
    - automation.eingangsture_fur_mehr_als_5_minuten_offen
    - automation.eingangsture_offnet
    - automation.eingangsture_schliesst
    - automation.eingangsture_statusanderung
    - automation.eingangsture_statusanderung_lang
    - automation.fehrnsehr_wird_ausgeschalten
    - automation.hass_status_report
    - automation.hass_update_available
    - automation.mark_person_as_away
    - automation.mark_person_as_extended_away
    - automation.mark_person_as_home
    - automation.mark_person_as_just_arrived
    - automation.mark_person_as_just_left
    - automation.rollladen_bei_hize_automatisch_schliessen
    - automation.rollladen_bei_wind_automatisch_offnen
    - automation.rollladen_mit_fehrnbedienung_offnen
    - automation.rollladen_mit_fehrnbedienung_schliessen
    - automation.sonnenaufgang_im_badezimmer
    - automation.sonnenaufgang_im_schlafzimmer
    - automation.sonnenaufgang_im_wohnzimmer
    - automation.sonnenaufgang_im_zimmer_1
    - automation.sonnenaufgang_im_zimmer_2
    - automation.sonnenuntergang_im_badezimmer
    - automation.sonnenuntergang_im_schlafzimmer
    - automation.sonnenuntergang_im_wohnzimmer
    - automation.sonnenuntergang_im_zimmer_1
    - automation.sonnenuntergang_im_zimmer_2
    - automation.terrassenture_offnet
    - automation.terrassenture_schliesst
    - automation.wecker

automation:
  view: no
  entities:
    - group.all_sceens
    - group.all_automations

