zimmer2_automations:
  view: no
  entities:
    - automation.sonnenaufgang_im_zimmer_2
    - automation.sonnenuntergang_im_zimmer_2

zimmer2:
  name: Zimmer 2
  view: yes
  entities:
    - sensor.zimmer2_temperatur
    - sensor.zimmer2_feuchtigkeit
    - group.zimmer2_automations
    - cover.zimmer2_rollo
    - light.zimmer_2
